"""update schema

Revision ID: 320f841ec0b9
Revises: 
Create Date: 2026-05-01 02:05:51.435955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '320f841ec0b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('election_id', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('post', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('resume_path', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('photo_path', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='candidatestatus'), nullable=True))
    op.create_unique_constraint(None, 'candidates', ['student_id'])
    op.create_foreign_key(None, 'candidates', 'elections', ['election_id'], ['id'])
    op.drop_column('candidates', 'position')
    op.add_column('elections', sa.Column('status', sa.Enum('upcoming', 'active', 'completed', name='electionstatus'), nullable=True))
    op.add_column('elections', sa.Column('results_status', sa.String(), nullable=True))
    op.add_column('elections', sa.Column('publish_date', sa.DateTime(), nullable=True))
    op.alter_column('elections', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('elections', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('elections', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('elections_name_key'), 'elections', type_='unique')
    op.add_column('students', sa.Column('is_candidate', sa.Boolean(), nullable=True))
    op.add_column('votes', sa.Column('post', sa.String(), nullable=False))
    op.create_unique_constraint('unique_vote_per_post', 'votes', ['student_id', 'election_id', 'post'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_vote_per_post', 'votes', type_='unique')
    op.drop_column('votes', 'post')
    op.drop_column('students', 'is_candidate')
    op.create_unique_constraint(op.f('elections_name_key'), 'elections', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('elections', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('elections', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('elections', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('elections', 'publish_date')
    op.drop_column('elections', 'results_status')
    op.drop_column('elections', 'status')
    op.add_column('candidates', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='unique')
    op.drop_column('candidates', 'status')
    op.drop_column('candidates', 'photo_path')
    op.drop_column('candidates', 'resume_path')
    op.drop_column('candidates', 'post')
    op.drop_column('candidates', 'election_id')
    # ### end Alembic commands ###
