"""added roll no to student and timestamp to vote

Revision ID: 7059e5029738
Revises: 5cd24c830161
Create Date: 2026-05-01 13:41:36.939730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7059e5029738'
down_revision: Union[str, Sequence[str], None] = '5cd24c830161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('roll_no', sa.String(), nullable=True))
    op.create_index(op.f('ix_students_roll_no'), 'students', ['roll_no'], unique=True)
    op.add_column('votes', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'timestamp')
    op.drop_index(op.f('ix_students_roll_no'), table_name='students')
    op.drop_column('students', 'roll_no')
    # ### end Alembic commands ###
